networks:
  backend: {driver: bridge}
  frontend: {driver: bridge}
services:
  api:
    container_name: mirzat_api
    depends_on: [php-fpm]
    environment: [VIRTUAL_HOST=api.mirzat.com.local]
    expose: [80, 443]
    image: mirzatsoft/nginx
    networks: [frontend, backend]
    volumes: ['../src/:/var/www:cached', './images/logs/nginx/:/var/log/nginx', './nginx/sites//api/http.conf.template:/etc/nginx/sites-available/http.conf']
  front:
    container_name: mirzat_front
    depends_on: [php-fpm]
    environment: [VIRTUAL_HOST=front.mirzat.com.local]
    expose: [80, 443]
    image: mirzatsoft/nginx
    networks: [frontend, backend]
    volumes: ['../src/:/var/www:cached', './images/logs/nginx/:/var/log/nginx', './nginx/sites//front/http.conf.template:/etc/nginx/sites-available/http.conf']
  local-proxy:
    container_name: mirzat_local-proxy
    image: jwilder/nginx-proxy
    networks: [frontend]
    ports: ['80:80', '443:443']
    volumes: ['/var/run/docker.sock:/tmp/docker.sock:ro', './images/logs/nginx/:/var/log/nginx']
  mysql:
    container_name: mirzat_mysql
    environment: [MYSQL_DATABASE=default, MYSQL_USER=default, MYSQL_PASSWORD=secret,
      MYSQL_ROOT_PASSWORD=root, TZ=UTC]
    image: mirzatsoft/mysql
    networks: [backend]
    ports: ['3306:3306']
    volumes: ['~/.mirzat/dock/data/mysql:/var/lib/mysql', './images/mysql/docker-entrypoint:/docker-entrypoint-initdb.d']
  php-fpm:
    container_name: mirzat_php-fpm
    environment: [PHP_IDE_CONFIG=serverName=php-fpm]
    expose: ['9000']
    extra_hosts: ['dockerhost:10.0.75.1']
    image: mirzatsoft/php-fpm
    networks: [backend]
    volumes: ['./images/php-fpm/php7.2.ini:/usr/local/etc/php/php.ini', '../src/:/var/www:cached']
  php-worker:
    container_name: mirzat_php-worker
    depends_on: [workspace]
    extra_hosts: ['dockerhost:10.0.75.1']
    image: mirzatsoft/php-worker
    networks: [backend]
    volumes: ['../src/:/var/www:cached']
  redis:
    container_name: mirzat_redis
    image: mirzatsoft/redis
    networks: [backend]
    ports: ['6379:6379']
    volumes: ['~/.mirzat/dock/data/redis:/data']
  swagger-editor:
    container_name: mirzat_swagger-editor
    environment: [VIRTUAL_HOST=swagger-editor.mirzat.com.local]
    expose: [8080]
    image: swaggerapi/swagger-editor
    networks: [frontend]
  workspace:
    container_name: mirzat_workspace
    environment: [PHP_IDE_CONFIG=serverName=php-fpm]
    extra_hosts: ['dockerhost:10.0.75.1']
    image: mirzatsoft/workspace
    networks: [frontend, backend]
    ports: ['2222:22']
    tty: true
    volumes: ['../src/:/var/www:cached']
version: '3'
volumes:
  mysql: {driver: local}
  redis: {driver: local}
